<?php

/**
* Implementation of hook_permission().
*/
function mysearch_permission() {
 return array(
   'access mysearch' => array(
       'title' => 'Access My Search',
       'description' => 'Allows a user to access search results',
     )
   );
}


/**
* Implementation of hook_menu().
*/
function mysearch_menu() {
 $items['mysearch'] = array(
   'page callback' => 'mysearch_searchpage',
   'page arguments' => array(1),
   'access arguments' => array('access mysearch'),
   'type' => MENU_SUGGESTED_ITEM,
   'file' => 'mysearch.inc',
   'file path' => drupal_get_path('module', 'mysearch'),
 );
 
 return $items;
}

/**
 * Implements hook_theme.
 */
function mysearch_theme($existing, $type, $theme, $path) {
  return array(
    'mysearch_layout' => array(
      'path' => drupal_get_path('module', 'mysearch') . '/theme',
      'template' => 'mysearch-layout',
      'variables' => array('data' => array()),
    ),
  );
}

